seed: 42
device: cuda
save_path: checkpoints

dataset:
    data_pos: bin/1
    data_neg: bin/0
    threshold: 0.95

loader:
    batch_size: 64

classifier:
    n_epochs: 50
    learning_rate: 3e-4
    path_model: bin
    path_log: bin.pickle
