seed: 42
device: cuda

dataset:
    data_pos: bin/1
    data_neg: bin/0
    threshold: 0.999 # доля белого
    pos_aug: 22
    neg_aug: 2

loader:
    batch_size: 8

siam:
    n_epochs: 20
    learning_rate: 1e-3
    path: m.pth

classifier:
    n_epochs: 10
    learning_rate: 1e-4
    path: c.pth

