seed: 42
device: cuda
save_path: checkpoints

dataset:
    data_pos: bin/1
    data_neg: bin/0
    threshold: 0.999 # доля белого
    pos_aug: 22
    neg_aug: 2

loader:
    batch_size: 8

siamese:
    n_epochs: 5
    learning_rate: 1e-3
    margin: 9
    train: True
    path_model: siamese
    path_log: siamese.pickle

classifier:
    n_epochs: 5
    learning_rate: 1e-4
    train: True
    path_model: classifier
    path_log: classifier.pickle
